name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: docker compose run --rm php71composer composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHP-CS-Fixer
        run: docker run --rm -v $(pwd):/code ghcr.io/php-cs-fixer/php-cs-fixer:${FIXER_VERSION:-3.57.0-php7.4} fix src

      - name: Check for changes and commit if any
        run: |
          current_branch=${{ github.ref_name }}
          git checkout "$current_branch"  # Check out the branch that triggered the workflow
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "Apply PHP-CS-Fixer changes"
            git push origin "$current_branch"  # Push the changes to the current branch
          fi
      - name: Run PHPUnit tests
        run: docker compose run --rm php71 vendor/bin/phpunit